spring.application.name=first
# Thymeleaf configuration
#spring.thymeleaf.prefix=classpath:/templates/
#spring.thymeleaf.suffix=.html
#spring.thymeleaf.mode=HTML
#spring.thymeleaf.cache=false

server.port=9090